README.md
Most of this is taken from forum or from config.txt (and added new one for Windows 7 Home computers).  Consolidating information here.
=> Adding Common Issues section.

.gitignore, CMakeLists.txt
This pull request is equal to the change in [xmr-stak-nvidia](https://github.com/fireice-uk/xmr-stak-nvidia/pull/15)
- throw an error if a compile dependency is not fulfilled
- add options to disable hard compile dependencies
- extend `.gitignore` (separate commit)
=> Topic feature complete build

README.md
Add overview about advanced compile options.
This pull request contains the documentation for the features in #73.
=> extend `README.txt`

cli-miner.cpp
add myself to the command line output
=> add psychocrypt to cmd output

autoAdjust.hpp
- fix method call
- remove local variables and use method member
=> fix amd stagger detection

autoAdjust.hpp, cli-miner.cpp, config.txt, jconf.cpp, jconf.h, xmr-stak-cpu.cbp
Needs AMD test - I wrote that part 100% dry, using only the AMD manual.
=> CPU autoconfig

CMakeLists.txt
=> fix wrong naming in CMake install

README.md
fix how to enable dynamic linking
=> fix documentation bug

cli-miner.cpp, config.txt, executor.cpp, executor.h, jconf.cpp, jconf.h
@psychocrypt can you verify this one. If you are ok with those changes I will create a patch file and apply them to all stak miners
=> Daemon mode

crypto/cryptonight_common.cpp, minethd.cpp, socks.h
This pull request adds modern FreeBSD support.
FreeBSD has some APIs looks like Apple, and some in it own style.
It was checked on FreeBSD 11.1-PRERELEASE with system compiler (clang 4.0.0) and looks to work fine.
=> Feature FreeBSD support

crypto/cryptonight_aesni.h
use single hash implementation within the function `cryptonight_double_hash`
The way how the single hash implementation is implemented is more efficient than the implementation from the double hash function. With the new implementation I get a small performance increase.
2 x Xeon(R) CPU E5-2630 v3 @ 2.40GHz - 4 threads double hash (low power mode) and 12 threads used single hash 
old: 905 H/s
PR: 929 H/s
= 2,6% improvement
i7-4600U CPU @ 2.10GHz compare 1 thread with double hash (low power mode)
old: 105 H/s
PR: 115 H/s 
= 9,5% improvement
The i7 run was only a test to compare the old low_power_mode with the new implementation, for the i7 two threads without low power mode are still faster (121 H/s)
=> optimize double hash implementation

hwlocMemory.hpp, minethd.cpp, minethd.h
- add function `bindMemoryToNUMANode()`
- add `affinity` member to `minethd`
=> hwloc NUMA memory binding

donate-level.h
add my wallet address to donate-level.h
=> add psychocrypt to donate-level.h

CMakeLists.txt
- add windows socket libraries
- search for windows name of all dependencies
- add missing link step to the intermediate static library
=> add Windows VS2017 support

autoAdjustHwloc.hpp
- use native hwloc bitmap to find hardware cores
- remove unused functions (not needed anymore)
Old behavior was that only the first 64 cores are used to map hashes to cores.
=> fix auto suggestion for 64+ cores

config.txt, jconf.cpp
Add a manual override for AES cpuid.
=> AES override feature

autoAdjustHwloc.hpp, minethd.cpp, minethd.h
This fixes #223 and another bug that I found in pre-release testing.
=> Topic bug squashing

config.txt
@psychocrypt as per our discussion I'm adding minemonero.pro along with a couple small pools that I think could use some extra traffic.
=> Update default pools

LINUXCOMPILE.md, scripts/build_xmr-stak_docker/build_xmr-stak_docker.sh
Build documentation improved and added "docker script" for building xmr-stak for other distributions
=> Build documentation improved and added "docker script" for building xmr-stak for other distributions

minethd.cpp, minethd.h
Fix for a race condition bug spotted by SChernykh ( #253 )
=> Race condition fix

config.txt
Fix several typos in config.txt dev branch
=> fix typos in config.txt

README.md
=> Fixes README.md typo

minethd.cpp, minethd.h
This should fix the crash reported in #345 - needs testing. Thanks to @aphex3k for finding the bug.
=> Fix due to uninitialised piNonce1 in double mode
