fireice-uk/xmr-stak-cpu

minethd.cpp
Simple check of cpuid to see if AES-NI instructions are supported. If they aren't the user is notified and the application exits gracefully. I tested this on Windows and Linux on boxes that both do and don't support AES-NI.
=> Checks cpuid to see if AES-NI instructions are supported

CMakeLists.txt
-static will compile, but causes a segment fault on both build and target. Using the new flags compiles cleanly and runs on both build and target. (Build = debian sid [testing], Target= debian jessie [stable])
=> Update static flags to fix seg fault

CMakeLists.txt, crypto/cryptonight_aesni.h, crypto/cryptonight_common.cpp, xmr-stak-cpu.cbp
The core CryptoNight functions are currently duplicated for the prefetch/no-prefetch condition. This patch unifies and parameterizes these functions; they are now templated with three inputs:
- `ITERATIONS`: the number of iterations of the scratchpad procedure
- `MEM`: the size of the scratchpad
- `PREFETCH`: whether or not the next location of the scratchpad should be prefetched using `_mm_prefetch` (see f59c4d1)
Since the functions are parameterized via compile-time constants there is 0% functional overhead -- the code generated by this patch for the CryptoNight functions should be completely identical to previous releases. In particular the `PREFETCH` `bool` should will compile to `if(true)` and `if(false)` which all compilers translate as simply including/excluding the succeeding …
=> Unify and parameterize CryptoNight functions

CMakeLists.txt, cli-miner.cpp, httpd.cpp
close #68
This pull request is in the most parts equal to the cmake changes in [xmr-stak-nvidia](https://github.com/fireice-uk/xmr-stak-nvidia/pull/10)
- allow compiling without microhttpd
- allow compiling without OpenSSL
- install `config.txt` with command `make install`
=> refactor CMake

CMakeLists.txt, README.md
close #75 
This pull request is not adding set all libraries are linked static. The reason for this is that the crypto libraries and microhttpd also use dlopen within the static libraries. I get no full static linked version running.
Therefore this version adds only the support to be independent from gcc5.1+.
- add cmake option `CMAKE_LINK_STATIC`
- add missing `CMAKE_C_FLAGS`
- change documentation
=> allow optional static linking

crypto/cryptonight_common.cpp
Increase the performance for systems without huge memory pages to the performance with huge pages.
Use 2 MiB alignment for memory allocations.
cpu | used threads | cache | this pr [hash/s] | version before pr [hash/s] | speedup [%] | system
:---|:------------:|:------------------|:------------------------|:------------|:------------|:----
2 x E5-2630 v3 @ 2.40GHz | 16 | 2x20MiB | 821 | 660 | 24 | ubuntu 14.04 no huge pages
i7-4600U CPU @ 2.10GHz | 2 | 4MiB | 117* | 86 | 36  | ubuntu 16.04 no huge pages
\* equal performace with huge pages
=> speedup systems without huge memory pages

config.txt, jconf.cpp
- allow to disable prefetch on systems without hardware aes
- set default disable memory prefetch
I tested #80
- with BMI2 hardware, with AES
- Intel E5-2630 v3
- Intel i7-4600U
- without BMI2 hardware, with AES
- Intel E5-2609
- AMD Opteron 627
- without BMI2, **without** AES
- Intel E5 750
- Intel i7 2530QM
and all cpus shows better or equal performance without memory prefetching than with enabled prefetch. We should ship the miner with settings those are achieve a high hash rate by default. Most results are documented in #78 .
@fireice-uk Do you have a system where `no_prefetch : false` is faster?
=> disable prefetch by default

CMakeLists.txt, README.md
- rename option `*_REQUIRED` to `*_ENABLE`
- allow to disable the dependency OpenSSL and microhttpd
- update README.md
=> allow to disable OpenSSL and microhttpd

CMakeLists.txt, README.md, autoAdjustHwloc.hpp, cli-miner.cpp
- `CMakeLists.txt` add find code to search for `hwloc`
- `autoAdjustHwloc.hpp` search optimal config based on hwloc topology
- update `README.txt`
If hwloc is disabled with the cmake flag `-DHWLOC_ENABLE=OFF` than the old auto adjust implementation is used.
-  [x] linux with L3 cache
- AMD Opteron 62766 4 Socket
- Intel i7 4600U
- E5 2630 v3 2 Socket
- ...
=> hwloc autoadjust

cli-miner.cpp
Save time stamp of the last for loop round outside of the loop.
This pull request limits the number of key those can pressed by the user to two per second.
=> fix console guard

.travis.yml
Initial Travis CI script added. It should help with #149 
You can see the example here: https://travis-ci.org/ruzickap/xmr-stak-cpu
To make Travis CI working for the project you need to configure + enable the xmr-stak-cpu on their web page.
=> Initial Travis CI script added

minethd.cpp
Follow up to https://github.com/fireice-uk/xmr-stak-cpu/pull/142 for mac support.  
This is on Mac OS Sierra 10.2.5 and AppleClang 8.1.0.8020042 as the c compiler.
Fixes #124.
=> Dev branch with mac fix

socks.h
I found there was an issue with compiling on Alpine linux. 
```
[ 72%] Building CXX object CMakeFiles/xmr-stak-cpu.dir/jpsock.cpp.o
In file included from /xmr-stak-cpu/jpsock.cpp:33:0:
/xmr-stak-cpu/socks.h: In function 'const char* sock_strerror(char*, size_t)':
/xmr-stak-cpu/socks.h:83:19: error: invalid conversion from 'int' to 'const char*' [-fpermissive]
return strerror_r(errno, buf, len);
~~~~~~~~~~^~~~~~~~~~~~~~~~~
make[2]: *** [CMakeFiles/xmr-stak-cpu.dir/build.make:183: CMakeFiles/xmr-stak-cpu.dir/jpsock.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:105: CMakeFiles/xmr-stak-cpu.dir/all] Error 2
make: *** [Makefile:130: all] Error 2
```
As Alpine does not use GLIBC this line is need well only the `!defined(__GLIBC__)` others are just a bonus.
=> Fixes building on Alpine Linux

README.md, WINCOMPILE.md
add documentation howto install all dependencies and compile with VS2017
To follow the instructions you need #160 as code base 
~~**WARNING** This pull request is currently under development . I wrote the documentation under linux and need to test all again in Windows.~~
@fireice-uk feel free to test it
=> windows compile HowTo

.appveyor.yml
Hello guys.
I would like to add the Appveyor CI functionality ( mentioned in #149 ) - which can build + test the source code on windows for every pull request.
I tried to follow the steps for windows build in #161 but I'm getting the error https://ci.appveyor.com/project/ruzickap/xmr-stak-cpu
I'm not a windows guy so I have no idea how to compile the source code using Visual Studio, but if you have time please let me know how to fix it to have this feature enabled in the future.
(Looks like some predefined variables for compilation are missing...)
Thank you...
=> Add appveyor initial file

autoAdjust.hpp, autoAdjustHwloc.hpp
Changing "Copy&Paste" output line to be easily parsable (showing BEGIN / END)
=> Changing "Copy&Paste" output line to be easily parsable (showing BEGIN / END)

minethd.cpp, socks.h
Missing cstring library when compiling with Alpine 3.6
=> Compile error on Alpine 3.6

socket.cpp
=> Fix handling of stratum+tcp:// format

autoAdjustHwloc.hpp
- fix exclusive cache detection
- fix usage of wrong cache size
This fixes the hash generation for the quad socket AMD opteron system,
=> fix rewrite of the hwloc autosuggestion

autoAdjustHwloc.hpp
- fix wrong implemented method `isCacheExclusive()`
- round up number of hashes if >= 1 MiB cache is available
=> fix wrong cache method

autoAdjustHwloc.hpp, hwlocMemory.hpp, minethd.cpp, xmr-stak-cpu.cbp
I had a few spare hours so I did a total rewrite of the allocation algorithm. It should do exactly the same thing (with some creative liberties). It has two important things for clarity:
- Separation of tree searching from the generic algorithm (this is a major actually, any kind of code-on-top-of-DFS goes spaghetti very soon)
- Proper error handling
=> HWLOC allocation algorithm cleanup

CMakeLists.txt, README.md
A common issue is that the user only install gcc in version 5.X but the C++ compiler is still pointing to a older version. To avoid this the README and CMake error message mentioned explicit that g++ >=5.1 is needed.
=> CMake: change GCC to g++ warning

crypto/c_keccak.c
I unrolled one of the loops in the `c_keccak.c` file and applied a slight optimization, noticing that one doesn't need to assign variables throughout the loop, just on the last iteration. It seems to have helped bump up the hash power a bit. Note that the highest H/s is higher for the PR than Dev. I repeated the test runs several times, always had an increase in highest H/s for PR than Dev (usually also, in the 2.5s, 60s, etc.).
**PR**
HASHRATE REPORT                             
| ID | 2.5s |  60s |  15m | ID | 2.5s |  60s |  15m |                                                                                                                        
|  0 | 55.4 | 54.9 | (na) |  1 | 55.3 | 56.1 | (na) | …
=> Slight keccak optimization

.appveyor.yml
disable OpenSSL to pass the CI
This is only a temporary solution to solve #235, OpenSSL should be enabled again before the next release.
=> fix appveyor tests

.appveyor.yml, WINCOMPILE.md
- update appveyor CI
- update `WINCOMPILE.md` guide
This PR re enable the use of OpenSSL for the windows CI.
THX @fireice-uk  for compile all dependencies.
=> use precompiled dependencies

README.md, version.h
This PR also update the version number with the postfix `dev`
=> merge master back to dev

.appveyor.yml, WINCOMPILE.md
@fireice-uk The version number is equal to the last release
- merge back appveyor fix (use precompiled dependencies)
- merge back installation guide for ubuntu 14.04
=> merge dev fixes back to master

CMakeLists.txt
Fixing bug in CMakeLists.txt preventing to pick up microhttpd library root as defined in environment variable "MICROHTTPD_ROOT"
Example: "export MICROHTTPD_ROOT=/opt/gnu/libmicrohttpd-0.9.55" will be ignored without this fix
=> Env variable "MICROHTTPD_ROOT" is ignored by cmake
